opal3/blueprints/OpalResources.py
import requests
import json

from flask import jsonify, Blueprint, render_template, flash, redirect, url_for, g, session, abort, request
from ..database import db, Orn, Algorithm, Source
from ..oidc import oidc
from werkzeug import exceptions

bp = Blueprint('OpalResources', __name__)

@bp.route('/orn/', methods=['GET'])
# @oidc.accept_token(True, ['openid'])
def orn_index():
    orns = Orn.query.all()
    cls = [o.json_obj() for o in orns]
    return jsonify(cls)


@bp.route('/orn/<cid>', methods=['GET'])
# @oidc.accept_token(True, ['openid'])
def orn_id(cid):
    pt = Orn.query.filter_by(id=cid).first()
    return jsonify(pt.json_obj())


@bp.route('/algorithm/', methods=['GET'])
# @oidc.accept_token(True, ['openid'])
def algoritm_index():
    algs = Algorithm.query.all()
    cls = [o.json_obj() for o in algs]
    return jsonify(cls)


@bp.route('/algorithm/<aid>', methods=['GET'])
# @oidc.accept_token(True, ['openid'])
def algorithm_id(aid):
    pt = Algorithm.query.filter_by(id=aid).first()
    return jsonify(pt.json_obj())


@bp.route('/source/', methods=['GET'])
# @oidc.accept_token(True, ['openid'])
def source_index():
    srcs = Source.query.all()
    cls = [o.json_obj() for o in srcs]
    return jsonify(cls)


@bp.route('/source/<sid>', methods=['GET'])
# @oidc.accept_token(True, ['openid'])
def source_id(sid):
    pt = Source.query.filter_by(id=sid).first()
    return jsonify(pt.json_obj())


@bp.errorhandler(500)
def server_error(e):
    return jsonify(error=500, text=str(e)), 500


@bp.errorhandler(404)
def page_not_found(e):
    return jsonify(error=404, text=str(e)), 404

opal3/blueprints/client.py
import requests
import json

from flask import jsonify, Blueprint, render_template, flash, redirect, url_for, g, session, abort, request
from ..database import db, Orn, User, PersonaProvider
from ..oidc import oidc
from werkzeug import exceptions

bp = Blueprint('client', __name__)


def get_persona_provider(id):
    pp = PersonaProvider.query.filter_by(name=id).first()
    if not pp:
        raise exceptions.NotFound("PersonalProvider not found.")
    return pp


@bp.route('/configuration/', methods=['GET'])
@oidc.require_access_token
def configuration():
    conf = oidc.get_configuration()
    return jsonify(conf)


@bp.route('/user_info/', methods=['GET'])
def user_info():
    token = oidc.get_access_token()
    if token:
        info = oidc.get_token_info(token)
        return jsonify(info)
    return jsonify({"message": "no token"})


@bp.route('/token_info/', methods=['GET'])
def token_info():
    token = oidc.get_access_token()
    if token:
        info = oidc.get_token_info(token)
        return jsonify(info)
    return jsonify({"message": "no token"})


@bp.route('/client/', methods=['GET'])
# @oidc.accept_token(False, ['openid'])
@oidc.require_access_token
def index():
    ds_clients = PersonaProvider.query.all()
    cls = [cl.json_obj() for cl in ds_clients]
    return jsonify(cls)


@bp.route('/client/<pid>', methods=['DELETE'])
@oidc.require_access_token
def delete(pid):
    pp = get_persona_provider(pid)
    db.session.delete(pp)
    db.session.commit()
    return jsonify(text="deleted"), 200


@bp.route('/client/<pid>', methods=['GET'])
@oidc.require_access_token
def details(pid):
    pp = get_persona_provider(pid)
    return jsonify(pp.json_obj())


@bp.route('/client/', methods=['POST'])
@oidc.require_access_token
def register():
    client_obj = request.get_json()

    # TODO: validate client_obj required properties

    email = g.sub

    # TODO: verify scope list
    scopes = client_obj.pop('scopes', None)
    # scopes are on the DP - therefore not able to query in the database.
    # commenting it out
    #selected_orns = Orn.query.filter(Orn.name.in_(scopes)).all()
    #client_obj['scope'] = " ".join(["{}:{}".format(s.id,s.name) for s in selected_orns])
    client_obj['scope'] = " ".join(scopes)

    client_obj['contacts'] = [email]

    pt = PersonaProvider()
    pt.name = client_obj['client_name']


    # remove description from OIDC request
    pt.description = client_obj.pop('description', None)
    pt.recurring = client_obj.pop('recurring', False)
    pt.result_url = client_obj.pop('result_url', None)
    # pt.user_id = g.sub
    pt.oidc_request = json.dumps(client_obj)

    try:
        r = oidc.register_client(client_obj)
        pt.oidc_response = json.dumps(r)
        db.session.add(pt)
        db.session.commit()

        return jsonify(pt.json_obj())
    except Exception as err:
        print(err)
        raise exceptions.InternalServerError()


@bp.errorhandler(500)
def server_error(e):
    return jsonify(error=500, text=str(e)), 500


@bp.errorhandler(404)
def page_not_found(e):
    return jsonify(error=404, text=str(e)), 404

opal3/blueprints/worker.py
import requests
import json

from flask import jsonify, Blueprint, render_template, flash, redirect, url_for, g, session, abort, request
from ..database import db, Orn, User, PersonaProvider
from ..oidc import oidc
from werkzeug import exceptions
import datetime

bp = Blueprint('worker', __name__)

@bp.route('/submit_request/', methods=['POST'])
def submit_request():
    token = oidc.get_access_token()
    if not token:
        return jsonify({"message": "no token"}), 401

    # Get token info
    info = oidc.get_token_info(token)
    scopes = info["scope"].split(' ')
    client_id = info['client_id']
    user_id = info['user_id']

    # Get job info with structure
    """
    {
        id: job_id,
        orn: opal resource name,
        sync: true/false - should the result be returned or submited into url,
        url: url to post results,
        params: [] - array of parameter objects
    }
    """
    print(info)
    job = request.get_json()

    # Check if job.orn is in scopes list
    try:
        if job['orn'] not in info["scope"].split(" "):
            return jsonify(error=400, message="orn not in scope1"), 400
    except:
        return jsonify(error=400, message="orn not in scope2"), 400

    orn = Orn.query.filter_by(name=job["orn"]).first()
    if not orn:
        return jsonify(error=400, message="orn not found"), 400

    print(orn.json_obj())
    sources = orn.sources
    algs = orn.algorithms
    dt = datetime.datetime.utcnow()

    ret_val = {
        "sources": [s.json_obj() for s in sources],
        "algorithms": [a.json_obj() for a in algs],
        "datetime": dt,
        "client_id": client_id,
        "user_id": user_id
    }
    print(ret_val)
    return jsonify(ret_val), 200

opal3/templates/base.html
{# ``base.html`` is the template all our other templates derive from. While
Flask-Bootstrap ships with its own base, it is good form to create a custom
one for our app, as it allows customizing some aspects.

Deriving from bootstap/base.html gives us a basic page scaffoling.

You can find additional information about template inheritance at

http://jinja.pocoo.org/docs/templates/#template-inheritance
#}
{%- extends "bootstrap/base.html" %}

{% block title %}OPAL CoreID Provider{% endblock %}

{% import "bootstrap/fixes.html" as fixes %}

{% block head %}
{{super()}}
{{fixes.ie8()}}
{%- endblock %}

{% block styles -%}
{{super()}}

<link rel="stylesheet" type="text/css"
      href="{{url_for('static', filename='style.css')}}">
{% endblock %}

{# Finally, round things out with navigation #}
{% block navbar %}
<div class="container">
    {{nav.opalnavbar.render()}}

    {% import "bootstrap/utils.html" as utils %}
    {%- with messages = get_flashed_messages(with_categories=True) %}
    {%- if messages %}
    <div class="row">
        <div class="col-md-12">
            {{utils.flashed_messages(messages)}}
        </div>
    </div>
    {%- endif %}
    {%- endwith %}
</div>
{% endblock %}

opal3/templates/client/details.html
{%- extends "base.html" %}
{% block content %}
    {% if client %}
        Request:  <pre>{{client.request_json}}</pre>
        Response: <pre>{{client.response_json}}</pre>
    {% else %}
        <p>{{error}}</p>
    {% endif %}
{%- endblock %}

opal3/templates/client/index.html
{%- extends "base.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Registered Personas</h1>
    </div>
    <div>
        <a class="btn btn-default" href="{{url_for('client.register')}}">Create new</a>
    </div>
    <div>
        <ul class="list-group">
        {% for dsc in dsclients %}
            <li class="list-group-item">
                <a href="{{ url_for('client.details', id=dsc.id) }}">{{dsc.name}}</a>
            </li>
        {% else %}
            <li class="list-group-item">No registered personas</li>
        {% endfor %}
        </ul>
    </div>
</div>
{%- endblock %}

opal3/templates/client/register.html
{%- extends "base.html" %}
{% block content %}
<div class="container">
    <form action="{{ url_for('client.register') }}" method="POST" class="add-entry">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" aria-describedby="nameHelp"
                   placeholder="Enter name" name="name"/>
            <small id="nameHelp" class="form-text text-muted">Name of the client.</small>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description" rows="5" cols="40"
                      aria-describedby="descriptionHelp"></textarea>
            <small id="descriptionHelp" class="form-text text-muted">Short description.</small>
        </div>
        <div class="form-group">
            <label for="orn">ORN</label>
            <select multiple class="form-control" name="orn" id="orn" aria-describedby="ORNHelp">
                    {% for orn in orns %}
                    <option value="{{orn.id}}">{{orn.name}}</option>
                    {% else %}
                    <option value="-1" disabled="disabled">No ORNs</option>
                    {% endfor %}
                </select>
            <small id="ORNHelp" class="form-text text-muted">ORN for this client.</small>
        </div>
        <div class="form-check">
            <label for="recurring" class="form-check-label">
                <input type="checkbox" class="form-check-input" id="recurring" aria-describedby="recurringHelp"
                   name="recurring"/>
                Recurring
            </label>
            <div>
                <small id="recurringHelp" class="form-text text-muted">Recurring job.</small>
            </div>
        </div>
        <br/>
        <div class="form-group">
            <label for="redirect_url">Redirect URL</label>
            <input type="text" class="form-control" id="redirect_url" aria-describedby="redirectUrlHelp"
                   placeholder="http://example.com/oidc_callback" name="redirect_url"/>
            <small id="RedirectUrlHelp" class="form-text text-muted">Redirect URL for the client Application.</small>
        </div>
        <br/>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Register</button>
        </div>
    </form>
</div>
{%- endblock %}

opal3/templates/index.html
{# This simple template derives from ``base.html``. See ``base.html`` for
more information about template inheritance. #}
{%- extends "base.html" %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>OPAL CoreID Provider PoC</h1>
    </div>
</div>
{%- endblock %}